import { Sparkle, Sparkles, WandSparkles } from "lucide-react";
import { ModelConfig, ReasoningEffortConfig } from "./types";
import {
  Google,
  OpenAI,
  Anthropic,
  DeepSeek,
  Meta,
  Grok,
  FalAi,
  Gemini,
} from "@/components/provider-icons";

export const REASONING_EFFORTS: ReasoningEffortConfig[] = [
  {
    id: "low",
    icon: Sparkle,
  },
  {
    id: "medium",
    icon: Sparkles,
  },
  {
    id: "high",
    icon: WandSparkles,
  },
];

export const AVAILABLE_MODELS: ModelConfig[] = [
  {
    id: "google/gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    icon: <Gemini />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    default: true,
    imageInput: true,
    pdfInput: true,
    search: true,
  },
  {
    id: "google/gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    icon: <Gemini />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    reasoning: true,
    imageInput: true,
    pdfInput: true,
    search: true,
  },
  {
    id: "openai/gpt-4.1",
    name: "GPT-4.1",
    icon: <OpenAI />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    imageInput: true,
    pdfInput: true,
    search: true,
  },
  {
    id: "openai/gpt-4.1-mini",
    name: "GPT-4.1 Mini",
    icon: <OpenAI />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    imageInput: true,
    pdfInput: true,
    search: true,
  },
  {
    id: "openai/gpt-4.1-nano",
    name: "GPT-4.1 Nano",
    icon: <OpenAI />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    imageInput: true,
    pdfInput: true,
    search: true,
  },
  {
    id: "openai/o4-mini",
    name: "o4-mini",
    icon: <OpenAI />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    reasoning: true,
    imageInput: true,
    pdfInput: true,
    search: true,
  },
  {
    id: "o3",
    name: "o3",
    icon: <OpenAI />,
    providerId: "openai",
    providerName: "OpenAI",
    reasoning: true,
    imageInput: true,
    pdfInput: true,
    search: true,
  },
  {
    id: "anthropic/claude-sonnet-4",
    name: "Claude 4 Sonnet",
    icon: <Anthropic />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    imageInput: true,
    pdfInput: true,
    search: true,
  },
  {
    id: "anthropic/claude-sonnet-4-thinking",
    name: "Claude 4 Sonnet (Thinking)",
    icon: <Anthropic />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    reasoning: true,
    imageInput: true,
    pdfInput: true,
    search: true,
  },
  {
    id: "anthropic/claude-opus-4",
    name: "Claude 4 Opus",
    icon: <Anthropic />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    imageInput: true,
    pdfInput: true,
    search: true,
  },
  {
    id: "anthropic/claude-opus-4-thinking",
    name: "Claude 4 Opus (Thinking)",
    icon: <Anthropic />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    reasoning: true,
    imageInput: true,
    pdfInput: true,
    search: true,
  },
  {
    id: "deepseek/deepseek-chat-v3-0324",
    name: "DeepSeek v3 0324",
    icon: <DeepSeek />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    search: true,
  },
  {
    id: "deepseek/deepseek-r1-0528",
    name: "DeepSeek R1 0528",
    icon: <DeepSeek />,
    providerId: "openrouter",
    reasoning: true,
    providerName: "OpenRouter",
    search: true,
  },
  {
    id: "meta-llama/llama-4-maverick",
    name: "Llama 4 Maverick",
    icon: <Meta />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    imageInput: true,
    search: true,
  },
  {
    id: "meta-llama/llama-4-scout",
    name: "Llama 4 Scout",
    icon: <Meta />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    imageInput: true,
    search: true,
  },
  {
    id: "x-ai/grok-3",
    name: "Grok 3",
    icon: <Grok />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    search: true,
  },
  {
    id: "x-ai/grok-3-mini",
    name: "Grok 3 Mini",
    icon: <Grok />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    reasoning: true,
    search: true,
  },
  {
    id: "gpt-image-1",
    name: "GPT ImageGen",
    icon: <OpenAI />,
    providerId: "openai",
    providerName: "OpenAI",
    imageGeneration: true,
  },
  {
    id: "fal-ai/flux-pro/v1.1-ultra",
    name: "FLUX Pro v1.1 Ultra",
    icon: <FalAi />,
    providerId: "falai",
    providerName: "FalAI",
    imageGeneration: true,
  },
  {
    id: "imagen-4.0-generate-preview-06-06",
    name: "Imagen 4",
    icon: <Google />,
    providerId: "vertex",
    providerName: "Vertex",
    imageGeneration: true,
  },
  {
    id: "imagen-4.0-fast-generate-preview-06-06",
    name: "Imagen 4 Fast",
    icon: <Google />,
    providerId: "vertex",
    providerName: "Vertex",
    imageGeneration: true,
  },
  {
    id: "imagen-4.0-ultra-generate-preview-06-06",
    name: "Imagen 4 Ultra",
    icon: <Google />,
    providerId: "vertex",
    providerName: "Vertex",
    imageGeneration: true,
  },
];
