import { Sparkle, Sparkles, WandSparkles } from "lucide-react";
import { ModelConfig, ReasoningEffortConfig } from "./types";
import {
  OpenAI,
  Anthropic,
  DeepSeek,
  Meta,
  Grok,
  FalAi,
  Gemini,
} from "@/components/provider-icons";

export const REASONING_EFFORTS: ReasoningEffortConfig[] = [
  {
    id: "low",
    icon: Sparkle,
  },
  {
    id: "medium",
    icon: Sparkles,
  },
  {
    id: "high",
    icon: WandSparkles,
  },
];

export const AVAILABLE_MODELS: ModelConfig[] = [
  {
    id: "google/gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    icon: <Gemini />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    default: true,
    features: ["imageInput", "pdfInput", "webSearch"],
  },
  {
    id: "google/gemini-2.5-flash-lite-preview-06-17",
    name: "Gemini 2.5 Flash Lite",
    icon: <Gemini />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    features: ["imageInput", "pdfInput", "webSearch"],
  },
  {
    id: "google/gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    icon: <Gemini />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    features: ["reasoning", "setEffort", "imageInput", "pdfInput", "webSearch"],
  },
  {
    id: "openai/gpt-4.1",
    name: "GPT-4.1",
    icon: <OpenAI />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    features: ["imageInput", "pdfInput", "webSearch"],
  },
  {
    id: "openai/gpt-4.1-mini",
    name: "GPT-4.1 Mini",
    icon: <OpenAI />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    features: ["imageInput", "pdfInput", "webSearch"],
  },
  {
    id: "openai/gpt-4.1-nano",
    name: "GPT-4.1 Nano",
    icon: <OpenAI />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    features: ["imageInput", "pdfInput", "webSearch"],
  },
  {
    id: "openai/o4-mini",
    name: "o4-mini",
    icon: <OpenAI />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    features: ["reasoning", "setEffort", "imageInput", "pdfInput", "webSearch"],
  },
  {
    id: "o3",
    name: "o3",
    icon: <OpenAI />,
    providerId: "openai",
    providerName: "OpenAI",
    features: ["reasoning", "setEffort", "imageInput", "pdfInput", "webSearch"],
  },
  {
    id: "anthropic/claude-sonnet-4",
    name: "Claude 4 Sonnet",
    icon: <Anthropic />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    features: ["imageInput", "pdfInput", "webSearch"],
  },
  {
    id: "anthropic/claude-sonnet-4-thinking",
    name: "Claude 4 Sonnet (Thinking)",
    icon: <Anthropic />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    features: ["reasoning", "setEffort", "imageInput", "pdfInput", "webSearch"],
  },
  {
    id: "anthropic/claude-opus-4",
    name: "Claude 4 Opus",
    icon: <Anthropic />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    features: ["imageInput", "pdfInput", "webSearch"],
  },
  {
    id: "anthropic/claude-opus-4-thinking",
    name: "Claude 4 Opus (Thinking)",
    icon: <Anthropic />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    features: ["reasoning", "setEffort", "imageInput", "pdfInput", "webSearch"],
  },
  {
    id: "deepseek/deepseek-chat-v3-0324",
    name: "DeepSeek v3 0324",
    icon: <DeepSeek />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    features: ["webSearch"],
  },
  {
    id: "deepseek/deepseek-r1-0528",
    name: "DeepSeek R1 0528",
    icon: <DeepSeek />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    features: ["reasoning", "webSearch"],
  },
  {
    id: "meta-llama/llama-4-maverick",
    name: "Llama 4 Maverick",
    icon: <Meta />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    features: ["imageInput", "webSearch"],
  },
  {
    id: "meta-llama/llama-4-scout",
    name: "Llama 4 Scout",
    icon: <Meta />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    features: ["imageInput", "webSearch"],
  },
  {
    id: "x-ai/grok-3",
    name: "Grok 3",
    icon: <Grok />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    features: ["webSearch"],
  },
  {
    id: "x-ai/grok-3-mini",
    name: "Grok 3 Mini",
    icon: <Grok />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    features: ["reasoning", "setEffort", "webSearch"],
  },
  {
    id: "x-ai/grok-4",
    name: "Grok 4",
    icon: <Grok />,
    providerId: "openrouter",
    providerName: "OpenRouter",
    features: ["reasoning", "imageInput", "webSearch"],
  },
  {
    id: "gpt-image-1",
    name: "GPT ImageGen",
    icon: <OpenAI />,
    providerId: "openai",
    providerName: "OpenAI",
    features: ["imageGeneration"],
  },
  {
    id: "fal-ai/flux-pro/v1.1-ultra",
    name: "FLUX Pro v1.1 Ultra",
    icon: <FalAi />,
    providerId: "falai",
    providerName: "FalAI",
    features: ["imageGeneration"],
  },
];
