const greetings = (name: string) => [
  `How can I help you, ${name}?`,
  `What can I do for you, ${name}?`,
  `What's on your mind, ${name}?`,
  `How can I assist you, ${name}?`,
  `Where should we begin, ${name}?`,
  `Good to see you, ${name}!`,
  `Nice to see you, ${name}!`,
  `Welcome back, ${name}!`,
  `Ready when you are, ${name}!`,
  `What are we tackling today?`,
  `Back for more? I like it.`,
  `Hit me with your wildest idea.`,
  `Let’s build something cool.`,
  `What's cooking, ${name}?`,
  `Yo. What’s the vibe today?`,
  `Let’s make your brain do backflips.`,
  `Here to make your life 2% easier.`,
  `Let's do this.`,
  `Welcome back, legend.`,
  `Missed ya, ${name}. What’s next?`,
  `Let’s solve something.`,
  `Feeling curious? Same.`,
  `Bored? I can help!`,
  `Got something big or just vibing?`,
  `Hi. Yes. I’m real-ish.`,
  `Let’s turn thoughts into actions.`,
  `Ideas? Problems? Chaos? I’m in.`,
  `Alright, ${name}, what now?`,
  `Let’s get those neurons firing.`,
  `Open tab. Open mind.`,
  `Welcome to your second brain.`,
  `Surprise me. Or don’t. I’m ready.`,
];

const promptSuggestions = [
  "Suggest a quick and healthy dinner recipe",
  "Explain quantum computing in simple terms",
  "Help me plan a weekend trip to Paris",
  "Create a workout routine for beginners",
  "What are some alternatives to caffeine?",
  "Give me a productivity tip I haven’t heard before",
  "Tell me a random science fact that sounds fake but isn’t",
  "How can I start meditating without it feeling weird?",
  "What should I watch if I loved Black Mirror?",
  "Break down the basics of investing for beginners",
  "How do I get better at small talk?",
  "Tell me something cool about space",
  "Make up a creative startup idea",
  "Teach me a weird word and what it means",
  "How do I make my resume stand out?",
  "What’s a brain teaser that will stump my friends?",
  "Give me a daily journaling prompt",
  "Explain how AI learns in a way a 10-year-old could get",
  "What’s one thing I should learn that no one talks about?",
  "How do I survive a long flight without losing my mind?",
  "Make a meal plan for someone who hates cooking",
  "Help me write a polite email to decline something",
  "Tell me a historical event with wild plot twists",
  "What are underrated habits that improve mental health?",
  "Give me a fun fact about the human body",
  "How do I beat procrastination today?",
  "What’s a life hack using only stuff in my kitchen?",
  "Explain cryptocurrency without the hype",
  "What’s something fun to do alone on a weekend?",
  "Give me a list of books that will change how I think",
  "Describe a futuristic invention that should exist",
  "Make me a to-do list template I’ll actually use",
  "How can I get better at learning things faster?",
  "What’s a niche hobby I might get obsessed with?",
  "Help me come up with a clever Instagram caption",
];

export const imageGenerationPrompts = [
  "A futuristic city glowing at sunset, with flying cars and glass towers",
  "A cozy reading nook filled with plants, soft pillows, and warm lighting",
  "A rainy cyberpunk street at night, neon signs reflecting on wet pavement",
  "A majestic dragon soaring over snow-covered mountains under a purple sky",
  "A minimalist workspace with a sleek laptop, coffee, and natural light",
  "An alien desert landscape with two moons and strange rock formations",
  "A chonky cat astronaut floating near a space station, Earth in the background",
  "An ancient stone castle under a starry sky with glowing windows",
  "A vintage café on a rainy evening, viewed from outside through foggy glass",
  "A humanoid robot painting a self-portrait in an artist’s studio",
  "A surreal forest where trees bend like waves and mushrooms glow",
  "Overgrown jungle ruins with vines, ancient statues, and scattered relics",
  "An epic interstellar battle with spaceships firing lasers across a nebula",
  "A glowing underwater city with domed structures and bioluminescent fish",
  "A giant steampunk airship hovering over a Victorian city",
  "A small cabin in a snowy forest, smoke rising from the chimney at dusk",
  "A magical library with floating books, spiral staircases, and glowing runes",
  "A cute frog wearing a wizard hat, sitting on a lily pad with a wand",
  "A solar eclipse over a cracked desert with strange shadows on the ground",
  "A retro 80s neon cityscape with grid roads and glowing palm trees",
  "A fairy lounging on a giant mushroom in a dreamy forest clearing",
  "A stormy sea with massive waves crashing into a dark pirate ship",
  "A sleek futuristic car speeding down a neon-lit highway at night",
  "A post-apocalyptic street with broken signs, vines, and an abandoned robot",
  "A whimsical village built on clouds, with floating houses and rope bridges",
  "A lone knight fighting a towering mech in a ruined battlefield",
  "A giant koi fish swimming through misty clouds like it's flying",
  "A fantasy tavern full of adventurers laughing, eating, and trading stories",
  "A haunted Victorian mansion on a foggy hill, windows glowing red",
  "A peaceful pixel art beach at sunset, with waves gently lapping in",
];

export const getRandomGreeting = (name: string) => {
  return greetings(name)[Math.floor(Math.random() * greetings(name).length)];
};

export const getRandomPromptSuggestions = (type: "text" | "image") => {
  let shuffled: string[] = [];
  if (type === "text") {
    shuffled = [...promptSuggestions].sort(() => 0.5 - Math.random());
  } else {
    shuffled = [...imageGenerationPrompts].sort(() => 0.5 - Math.random());
  }
  return shuffled.slice(0, 4);
};
