/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as SettingsIndexImport } from './routes/settings/index'
import { Route as SettingsKeysImport } from './routes/settings/keys'
import { Route as SettingsCustomizationImport } from './routes/settings/customization'
import { Route as ChatChatIdImport } from './routes/chat.$chatId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsIndexRoute = SettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsKeysRoute = SettingsKeysImport.update({
  id: '/settings/keys',
  path: '/settings/keys',
  getParentRoute: () => rootRoute,
} as any)

const SettingsCustomizationRoute = SettingsCustomizationImport.update({
  id: '/settings/customization',
  path: '/settings/customization',
  getParentRoute: () => rootRoute,
} as any)

const ChatChatIdRoute = ChatChatIdImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdImport
      parentRoute: typeof rootRoute
    }
    '/settings/customization': {
      id: '/settings/customization'
      path: '/settings/customization'
      fullPath: '/settings/customization'
      preLoaderRoute: typeof SettingsCustomizationImport
      parentRoute: typeof rootRoute
    }
    '/settings/keys': {
      id: '/settings/keys'
      path: '/settings/keys'
      fullPath: '/settings/keys'
      preLoaderRoute: typeof SettingsKeysImport
      parentRoute: typeof rootRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/settings/customization': typeof SettingsCustomizationRoute
  '/settings/keys': typeof SettingsKeysRoute
  '/settings': typeof SettingsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/settings/customization': typeof SettingsCustomizationRoute
  '/settings/keys': typeof SettingsKeysRoute
  '/settings': typeof SettingsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/settings/customization': typeof SettingsCustomizationRoute
  '/settings/keys': typeof SettingsKeysRoute
  '/settings/': typeof SettingsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/chat/$chatId'
    | '/settings/customization'
    | '/settings/keys'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/chat/$chatId'
    | '/settings/customization'
    | '/settings/keys'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/chat/$chatId'
    | '/settings/customization'
    | '/settings/keys'
    | '/settings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ChatChatIdRoute: typeof ChatChatIdRoute
  SettingsCustomizationRoute: typeof SettingsCustomizationRoute
  SettingsKeysRoute: typeof SettingsKeysRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ChatChatIdRoute: ChatChatIdRoute,
  SettingsCustomizationRoute: SettingsCustomizationRoute,
  SettingsKeysRoute: SettingsKeysRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/chat/$chatId",
        "/settings/customization",
        "/settings/keys",
        "/settings/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/chat/$chatId": {
      "filePath": "chat.$chatId.tsx"
    },
    "/settings/customization": {
      "filePath": "settings/customization.tsx"
    },
    "/settings/keys": {
      "filePath": "settings/keys.tsx"
    },
    "/settings/": {
      "filePath": "settings/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
